<Project Sdk="Microsoft.NET.Sdk">

  <!-- TargetFramework, Nullable and ImplicitUsings are set centrally in Directory.Build.props -->

  <ItemGroup>
    <ProjectReference Include="..\Ledger.Domain\Ledger.Domain.csproj" />
    <ProjectReference Include="..\Ledger.Application\Ledger.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
  </ItemGroup>

</Project>
