using Ledger.Application.Abstractions;
using Ledger.Domain.Entities;

namespace Ledger.Application.Tests.Fakes;

/// <summary>
/// A hand-written in-memory stand-in for <see cref="IAccountRepository"/>.
/// </summary>
/// <remarks>
/// Hand-written rather than generated by a mocking library. The interface has
/// two methods, so a fake is barely longer than the setup a mock would need, it
/// reads as ordinary code, and it lets a test assert on real stored state
/// instead of on which calls were made.
/// </remarks>
internal sealed class FakeAccountRepository : IAccountRepository
{
    private readonly Dictionary<Guid, Account> _accounts = [];

    public FakeAccountRepository(List<string>? callLog = null) => CallLog = callLog ?? [];

    /// <summary>Records call order so a test can assert it.</summary>
    public List<string> CallLog { get; }

    public int Count => _accounts.Count;

    public void Seed(Account account) => _accounts[account.Id] = account;

    public Account? Find(Guid id) => _accounts.TryGetValue(id, out var account) ? account : null;

    public Task<Account?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default)
    {
        CallLog.Add(nameof(GetByIdAsync));
        _accounts.TryGetValue(id, out var account);

        return Task.FromResult<Account?>(account);
    }

    public Task AddAsync(Account account, CancellationToken cancellationToken = default)
    {
        CallLog.Add(nameof(AddAsync));
        _accounts.Add(account.Id, account);

        return Task.CompletedTask;
    }
}
