using Ledger.Application.Abstractions;
using Ledger.Domain.Entities;

namespace Ledger.Application.Tests.Fakes;

/// <summary>
/// A hand-written in-memory stand-in for <see cref="IAccountRepository"/>.
/// </summary>
/// <remarks>
/// Hand-written rather than generated by a mocking library: the interface is
/// small, a fake reads as ordinary code, and it lets a test assert on real stored
/// state instead of on which calls were made.
/// </remarks>
internal sealed class FakeAccountRepository : IAccountRepository
{
    private readonly Dictionary<Guid, Account> _accounts = [];

    public FakeAccountRepository(List<string>? callLog = null) => CallLog = callLog ?? [];

    /// <summary>Records call order so a test can assert it.</summary>
    public List<string> CallLog { get; }

    /// <summary>Every set of identifiers a caller asked to lock, in the order asked.</summary>
    public List<IReadOnlyList<Guid>> LockRequests { get; } = [];

    public int Count => _accounts.Count;

    public void Seed(Account account) => _accounts[account.Id] = account;

    public Account? Find(Guid id) => _accounts.TryGetValue(id, out var account) ? account : null;

    public Task<Account?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default)
    {
        CallLog.Add(nameof(GetByIdAsync));
        _accounts.TryGetValue(id, out var account);

        return Task.FromResult<Account?>(account);
    }

    public Task<Account?> FindBySystemKeyAsync(string systemKey, CancellationToken cancellationToken = default)
    {
        CallLog.Add(nameof(FindBySystemKeyAsync));

        return Task.FromResult(_accounts.Values.FirstOrDefault(account => account.SystemKey == systemKey));
    }

    /// <remarks>
    /// Mirrors the real repository's contract: identifiers are de-duplicated and
    /// sorted, and accounts that do not exist are simply absent.
    /// </remarks>
    public Task<IReadOnlyList<Account>> GetForUpdateAsync(
        IReadOnlyCollection<Guid> ids,
        CancellationToken cancellationToken = default)
    {
        CallLog.Add(nameof(GetForUpdateAsync));

        var ordered = ids.Distinct().OrderBy(id => id).ToList();
        LockRequests.Add(ordered);

        IReadOnlyList<Account> locked = ordered
            .Select(Find)
            .Where(account => account is not null)
            .Select(account => account!)
            .ToList();

        return Task.FromResult(locked);
    }

    public Task AddAsync(Account account, CancellationToken cancellationToken = default)
    {
        CallLog.Add(nameof(AddAsync));
        _accounts.Add(account.Id, account);

        return Task.CompletedTask;
    }
}
